server:
  port: 8160    # 服务端口号

spring:
  application:
    name: service-user    # 服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_user?serverTimezone=GMT&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456        # mysql数据库连接
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #配置Nacos地址
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8       #返回json的全局时间格式
  redis:
    host: 192.168.202.134
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0     #配置redis

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #mybatis-plus日志


wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
yygh:
  baseUrl: http://localhost:3000        #微信扫码登录配置