#yml配置文件需注意：缩进、冒号后面需加空格！
server:
  port: 8204    # 服务端口


spring:
  application:
    name: service-msm    # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848     #配置Nacos地址  真服了 又弄半天，properties文件为什么不行？？？
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8       #返回json的全局时间格式
  redis:
    host: 192.168.202.135
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0     #配置redis

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest     #rabbitMQ配置

aliyun:
  sms:
    regionId: default
    accessKeyId: LT6I0Y5633pX89qC
    secret: jX8D04Dm12I3gGKj345FYSzu0fq8mT    #阿里云短信服务  没申请 用不了o(╥﹏╥)o


