#yml配置文件需注意：缩进、冒号后面需加空格！
server:
  port: 8206    # 服务端口

spring:
  application:
    name: service-order    # 服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?serverTimezone=GMT&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456        # mysql数据库连接
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #配置Nacos地址    坑死我了 得改成yaml文件才行
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8       #返回json的全局时间格式
  data:
    mongodb:
      uri: mongodb://192.168.202.135:27017/yygh_hosp    #引入mongoDB

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest     #rabbitMQ配置

  redis:
    host: 192.168.202.135
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0     #配置redis

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #mybatis-plus日志

weixin:
  appid: wx74862e0dfcf69954
  partner: 1558950191
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb     #微信支付配置(老师的 个人无法申请)
  cert: D:\\idea-workspace\\hospital_register\\service\\service_order\\src\\main\\resources\\cert\\apiclient_cert.p12